apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-web
  namespace: pi
  labels:
    kubernetes.courselabs.co: admission
spec:
  selector:
    matchLabels:
      app: pi-web
  template:
    metadata:
      labels:
        app: pi-web
    spec:
      containers:
        - image: kiamol/ch05-pi
          command: ["dotnet", "Pi.Web.dll", "-m", "web"]
          name: pi-web
          ports:
            - name: http
              containerPort: 80
