apiVersion: v1
kind: Service
metadata:
  name: pi-np
  namespace: pi
  labels:
    kubernetes.courselabs.co: admission
spec:
  ports:
    - port: 80
      nodePort: 30031
      targetPort: http
      name: http
  selector:
    app: pi-web
  type: NodePort